export const SPLASH_SCREEN = "SPLASH_SCREEN";

export const HOME_NAVIGATOR = "HOME_NAVIGATOR";

export const ORDER_TAB_NAVIGATOR = "ORDER_TAB_NAVIGATOR";
export const LIST_SCREEN = "LIST_SCREEN";
export const DETAIL_SCREEN = "DETAIL_SCREEN";
export const REPORT_SCREEN = "REPORT_SCREEN";
export const INTERNAL_MESSAGE_SCREEN = "INTERNAL_MESSAGE_SCREEN";

export const NOTIFICATION_TAB_NAVIGATOR = "NOTIFICATION_TAB_NAVIGATOR";
export const NOTIFICATION_SCREEN = "NOTIFICATION_SCREEN";

export const USER_TAB_NAVIGATOR = "USER_TAB_NAVIGATOR";
export const PROFILE_SCREEN = "PROFILE_SCREEN";
export const ABOUT_SCREEN = "ABOUT_SCREEN";
export const UPDATE_NAME_SCREEN = "UPDATE_NAME_SCREEN";
export const CHANGE_PASSWORD_SCREEN = "CHANGE_PASSWORD_SCREEN";
export const UPDATE_PHONE_SCREEN = "UPDATE_PHONE_SCREEN";
export const UPDATE_GENDER_SCREEN = "UPDATE_GENDER_SCREEN";
export const UPDATE_ADDRESS_SCREEN = "UPDATE_ADDRESS_SCREEN";
export const UPDATE_DESCRIPTION_SCREEN = "UPDATE_DESCRIPTION_SCREEN";

//

export const AUTH_SCREEN = "AUTH_SCREEN";
export const REGISTER_SCREEN = "REGISTER_SCREEN";
