export const SPLASH_SCREEN = "SPLASH_SCREEN";

export const MAIN_NAVIGATOR = "MAIN_NAVIGATOR";

export const HOME_TAB_NAVIGATOR = "HOME_TAB_NAVIGATOR";
export const HOME_SCREEN = "HOME_SCREEN";
export const HISTORY_SCREEN = "HISTORY_SCREEN";

export const AUTH_SCREEN = "AUTH_SCREEN";
export const REGISTER_SCREEN = "REGISTER_SCREEN";
